### ISSUE TITLE
Sample is missing...

### ISSUE THREAD

**Issue by samcov** [lukasoppermann/html5sortable#106]
The bower directory, and therefore the css & jquery.

jquery was easy to replace, the css, not so easy!

The example should be standalone, IMO.

**Comment by lukasoppermann** [comment]
Hey, just do a `bower install` and the sample should work fine. It was not standalone before, but relied on css downloaded from a cdn, which makes it dependent on an internet connection.

Now after you run `bower install` it should work fine, offline as well.

I do not want to be maintaining css in this repo, since it has nothing to do with the plugin at all. I much rather have that all external.

**Comment by samcov** [comment]
Thanks, it works!

**Comment by lukasoppermann** [comment]
Perfect! I will add a specific example section describing this to the readme, I guess it is easy to miss with the `npm i && bower install`.
