### ISSUE TITLE
AngularJS examples are broken

### ISSUE THREAD

**Issue by voidberg** [lukasoppermann/html5sortable#145]
AngularJS examples are not working anymore due to loading both src and dist code (and crashing due to module.exports).

**Comment by lukasoppermann** [comment]
Hey, are you sure it is due to the double loading? I added the double loading because when downloading the plugin via bower you do not get the src folder, so you need to use the dist folder, BUT when developing it makes sense to actually use the src folder, so that you can test your changes straight away. Maybe if this really crashes the examples we can add some kind of if-clause and asyncroniosly load either file, depending on its existence?

**Comment by lukasoppermann** [comment]
Actually this does in fact have nothing to do with the double loading. I removed it and it still fails. Anybody know whats wrong?
