### ISSUE TITLE
Is it possible to have an empty target list using 'connectWith'?

### ISSUE THREAD

**Issue by coderbydesign** [lukasoppermann/html5sortable#154]
Is it possible, when you have two lists that are connected, to move items from one list into an empty list? 

For example, you two lists, each with two items. You move both items from one list into the other, so there are now four items in one list, and none in the other. I can't seem to find a way to make it possible to move any of the four items into the now empty list.

Even in the example for connected lists it doesn't seem to be possible: http://lukasoppermann.github.io/html5sortable/examples/index.html

My case is that I have a list that's sometimes empty by default, and just want to have a target for populating the empty list from another.

Thanks!

**Comment by coderbydesign** [comment]
Of note: it does work as expected in the [original project demo](http://farhadi.ir/projects/html5sortable/), so maybe I'm missing something?

**Comment by lukasoppermann** [comment]
Hey @coderbydesign,
the desired behaviour should work fine, it does for me, event in the example pointed out.
**MAKE SURE** to add some padding to the list, because you need to drag the item **on to** the empty list, which if it is only 1px high is as good as impossible. :)

Please let me know if it works for you. (Maybe just add a padding and a red outline, so you see where you need to drag it to).

**Comment by coderbydesign** [comment]
Thanks for the response. Through more trial and error I did notice that yesterday in regards to the padding/styling to see the drop point. My initial issue was that I was using table rows inside a 'sortable' tbody, which you can't apply padding/min-height to, so that through me off for a while. I think I've been able to solve the issue by replicating table layout with an unordered list.

I appreciate the clarification!
