### ISSUE TITLE
Polymer wrapper

### ISSUE THREAD

**Issue by rodrigosancho** [lukasoppermann/html5sortable#234]
Hi guys!

I don't know if that's the most proper way to do this, but i just want to announce that I've made a wrapper for Polymer.

There's a fully working demo [here](https://trofrigo.github.io/polymer-html5sortable/). It's the same demo that you are using but made with Polymer. 

In order to do this I made a fork of your library and made some little modifications. If you want me to make a PR, just let me know.

Cheers!

**Comment by lukasoppermann** [comment]
Hey @trofrigo,

this is pretty neat. 👍 What modifications did you make that you would like to PR back into the project?

If you can post the link of the github repo I am very happy to add it to the readme.

**Comment by rodrigosancho** [comment]
Every time I need to find node children, I check before if Polymer is loaded, in this case, I use the Polymer's DOM API to find them.

The fork is [here](https://github.com/trofrigo/html5sortable), I changed only few lines.

**Comment by lukasoppermann** [comment]
Okay, so if I understand it correctly, the only change in the library is those lines: https://github.com/trofrigo/html5sortable/commit/63a801185a897704a87abed52c81f2cddf5337d3#diff-67116c8dd4789922d6d26a41f53121d6R447 correct?

We could add an option to add a custom selector function for this, so that you can (optionally) define what `_getChildren` does when initialising the package.

So basically if you could send a PR which includes:

- the _getChildren call where it is needed
- a change to the config object that allows the user to pass in their own function to be used by _getChildren
- the default function for _getChildren (which is basically like now, so just straight DOM API)

That would be awesome.

Once this is done you should be easily able to use the polymer adapter.

Anyway, I was actually asking for the link to the polymer adapter github repo, so I can link this. :D

**Comment by rodrigosancho** [comment]
The element's link is [https://github.com/trofrigo/polymer-html5sortable](https://github.com/trofrigo/polymer-html5sortable) ^^

I'm still finishing the PR

**Comment by rodrigosancho** [comment]
PR ready!

**Comment by lukasoppermann** [comment]
Thanks.
