### ISSUE TITLE
Method for serializing sorted order?

### ISSUE THREAD

**Issue by stevendesu** [lukasoppermann/html5sortable#236]
It would be nice if there were a convenient method for serializing the sorted order. Perhaps something like

```js
var order = sortable(".sortable", "serialize");
```

This could return an array of the elements IDs, in the newly sorted order. Or perhaps it could return something like the "data-sortable-id" attribute. Any way to easily get the list without having to traverse the DOM or track it separately on sortUpdate would be nice.

**Comment by lukasoppermann** [comment]
Hey @stevendesu, I really like this idea. I already worked on something like this quite a while ago, but never finished it.

I would really appreciate a PR. Best would be if the PR would include the changes to the readme & tests, as this would make it easiest to merge, but feel free to already add the send the PR in a "not merge ready" state, to get some input.

**Comment by cristimirt** [comment]
I also needed a way to get the current order of the items, so this is a quick hack that I made. Only works if the sorted items have an id. This will return an ordered array with the id's of the items. 

```javascript
/*
 * Get item id's in current order
 * Works only if each DOM item has an ID
 * @param {Element} sortableElement a single sortable
 */
 var _getOrder = function(sortableElement){
     var opts = _data(sortableElement, 'opts') || {}
     var items = _filter(_getChildren(sortableElement), opts.items)
     var ordered = []
     for (var index in items){
         ordered[index] = items[index]['id']
     }
     return ordered
 }
```

I also added it as a method for the **sortable** object.
```javascript
sortable.getOrder = function(sortableElement){
    _getOrder(sortableElement)
}
```

If you want to be able to use it like the other methods ( sortable('.sortable','getOrder')), you also need to add it to the list of public methods, in the declaration of **sortable** (line 502)
```javascript
if (/enable|disable|destroy|getOrder/.test(method)) {
```

The way I use it, is during the _**sortupdate**_ event. I add an extra element to the returned object
```javascript
ordered: _getOrder(sortableElement),
```

The reason I'm posting here instead of making a PR, is because this is just a hack and it wasn't properly tested. I'm also not a good JS developer. I'm posting it in case anyone else needs a quick way to do it.

**Comment by lukasoppermann** [comment]
Thank you @cristimirt for you help. You should now be able to write this functionality using the `serialize` method or by using the data provided on the `sortableUpdate` event.
