### ISSUE TITLE
Add new item on drag

### ISSUE THREAD

**Issue by Et3rnal** [lukasoppermann/html5sortable#289]
Great library first of all.

I'm trying to add item to my sortable list through dragging ?
The way I'm thing of it is this;
Drag an item "such as a button"
Capture that as it enters the sortable window
Turn it into a new item and show the place holder under it
Drop.

Is this possible? or this is not possible at least in this way? where to look/start?

**Comment by Et3rnal** [comment]
Okay I think i wasn't clear 💃 
So can I make the placeholder appears when im dragging something else (not an item from the list?) and one I "drop" it inset a new item? is there such a methods/call back?

So:
How to trigger the placeholder? is the first question

**Comment by lukasoppermann** [comment]
Hey @Et3rnal,

sadly this is not possible. What would be helpful to achieve this is a kind of clone feature like #62 but there is no active, working PR for this (feel free to send one if you want).

Otherwise you could create a sortable with one item in it and on sortupdate check if the item was removed, if so, you just add a new item to this list.

Hope that helps.

**Comment by Et3rnal** [comment]
Hey,

I'm not sure I got you.
So what I was able to achieve so far is to check which target under the mouse and then insert the new item before it. However, it's not working always as sometimes the mouse only sees the parent and not the items inside it. Also, I was hoping to get the placeholder to show but as soon as I have sortable initialized it clashes.

Maybe you could let me know what the dropped data should be to get it to work? Im trying to fool sortable that I'm actually moving an existing item.

ill check the cloning link.

**Comment by lukasoppermann** [comment]
Sortable adds some data to its items, when you add a new item to the list, you need to [`reload`](https://github.com/lukasoppermann/html5sortable#reload) the sortable to let it know about this new item. 

I think the way you are trying to add stuff does not work, but if you can link a jsfiddle so that I can check out the code I can tell you more.

**Comment by Et3rnal** [comment]
Ill try to make a jsfiddle.
I'm dragging the new item from a different environment "c# winforms".
At first, I just passed the values and appended a new item to the list using jQuery. But now I want to use html5sortable to avoid conflicts and benefits firm the features.

Reload should be easy to call on drag start or enter.

I remember the first error I got when I tried to drop an item instead of just data to let sortable handle it was the missing "parentElement"

**Comment by lukasoppermann** [comment]
Rereading it it sounds like #265 is that correct @Et3rnal ?

**Comment by Et3rnal** [comment]
Hmm, I guess it could be another way of doing it. I ended up developing my own dragDrop but I made it looks like its the same library.

Anyway, the client decided to cut down the features so I went back and just use this amazing library :)
I'm happy to share the code if anyone wants it (it's not clean, just a working draft that got killed)

**Comment by lukasoppermann** [comment]
Hey @Et3rnal I will not have time to clean it up and implement it, but it would be neat if you could share the code, if other people have a look into this issue they might find it useful.

**Comment by Et3rnal** [comment]
Exactly, I don't think its something to add to the library, but it definitely can help others. I'll share it the next time I work on it.
