### ISSUE TITLE
Table drop area limited to first column when forcePlaceholderSize is true

### ISSUE THREAD

**Issue by RianM** [lukasoppermann/html5sortable#294]
Hi,

As the title says, when you create a sortable table and set the forcePlaceholderSize to true, then the user can only drop the row into the first column.

JsFiddle example:
https://jsfiddle.net/MasterMedz/pk9u4m6x/1/

You can drag any row from any column, but it must be placed in the first column to actually move the row.

**Comment by lukasoppermann** [comment]
I can not reproduce the issue, what browser & OS are you using?

**Comment by RianM** [comment]
Sorry, I missed your response
I'm using Google Chrome on Windows 10
And I can still reproduce the error

**Comment by lukasoppermann** [comment]
Hey, I actually can reproduce the bug on Chrome 63 on Mac OSX.

However, the question now of course is why.

**Comment by lukasoppermann** [comment]
Hey, I found the issue and solution:

The issue is demonstrated here: https://jsfiddle.net/pk9u4m6x/6/
Basically without specifying a placeholder a div is used, however in tables the div will only fill the first column, thus you can not drop it further to the right. To fix this just specify a placeholder like on the demo page:

```
      sortable('.js-sortable-table', {
        items: "tr.js-sortable-tr",
        placeholder: "<tr><td colspan=\"3\"><span class=\"center\">The row will appear here</span></tr>",
        forcePlaceholderSize: false
      })
```
