### ISSUE TITLE
Wordpress implementation

### ISSUE THREAD

**Issue by Anchorage42** [lukasoppermann/html5sortable#350]
This might be a stupid question but how could I implement this code into a wordpress website?

**Comment by lukasoppermann** [comment]
Hey, no worries, totally fine. Assuming you are looking into implementing a sortable into a wordpress theme (or you have a theme based website) the easiest is to use to load `html5sortable.min.js` (download the zip from the [releases section!](https://github.com/lukasoppermann/html5sortable/releases)) and upload it with your theme. In there you can probably either include a standard js `<script>` tag to link to it or include it using the wordpress register method: [include js files into theme](https://code.tutsplus.com/articles/how-to-include-javascript-and-css-in-your-wordpress-themes-and-plugins--wp-24321).

There is also a possibility of using plugins like "Header and Footer Scripts" or something else.

However it is included you will also need to run `sortable('.your-sortable')` to turn whatever you want into a sortable. You can either do this in a script tag or in a second js file. However it needs to be done after `html5sortable.min.js` has loaded.

Does this help? Otherwise please provide some more specific information.
